# Generated by Django 6.1 on 2026-09-02 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_battle'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='accounts.battle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_bets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
