# Generated by Django 6.1 on 2026-09-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_wallettransaction'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='battlebet',
            constraint=models.UniqueConstraint(fields=('battle', 'user'), name='unique_battle_user'),
        ),
    ]
