# Generated by Django 6.1 on 2026-09-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_battlebet_unique_battle_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='max_players',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
