# Generated by Django 6.1 on 2026-09-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_battle_max_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
