# Generated by Django 6.1 on 2026-09-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_battle_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='nonce',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battle',
            name='server_seed',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='server_seed_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
