# Generated by Django 6.1.1 on 2026-09-07 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_battle_nonce_battle_server_seed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_hash_name', models.CharField(max_length=255)),
                ('asset_id', models.CharField(max_length=100, unique=True)),
                ('icon_url', models.URLField(blank=True)),
                ('float_value', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=10)),
                ('tradable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
