# Generated by Django 6.1.1 on 2026-09-08 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_inventoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlebet',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_bets', to='accounts.inventoryitem'),
        ),
    ]
