# Generated by Django 6.1.1 on 2026-09-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_battlebet_inventory_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
