# Generated by Django 6.1.1 on 2026-09-08 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_shoplisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplisting',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_listings', to='accounts.inventoryitem'),
        ),
    ]
