# Generated by Django 6.1.1 on 2026-09-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_platformwallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='asset_id',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='tradable',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='skinbattle_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('available', 'Доступен'), ('in_battle', 'В Battle'), ('frozen', 'Заморожен'), ('withdraw_pending', 'Выводится'), ('delivered', 'Выведен'), ('invalid', 'Недействителен')], default='available', max_length=30),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='tm_offer_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='tm_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('bet', 'Ставка'), ('win', 'Выигрыш'), ('commission', 'Комиссия'), ('deposit', 'Пополнение'), ('withdraw', 'Вывод'), ('shop_purchase', 'Покупка в магазине'), ('shop_sale', 'Продажа в магазине')], max_length=30),
        ),
    ]
