# Generated by Django 6.1.1 on 2026-09-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_inventoryitem_asset_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMMarketOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=100, unique=True)),
                ('market_hash_name', models.CharField(max_length=255)),
                ('tm_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item_class', models.CharField(blank=True, max_length=100)),
                ('item_instance', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('float_value', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
                ('phase', models.CharField(blank=True, max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
