# Generated by Django 6.1.1 on 2026-09-09 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_tmmarketoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('reserved', 'Зарезервировано'), ('completed', 'Завершено'), ('released', 'Освобождено')], default='reserved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='accounts.tmmarketoffer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
