# Generated by Django 6.1.1 on 2026-09-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_shopreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmmarketoffer',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
