# Generated by Django 6.1.1 on 2026-09-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_tmmarketoffer_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='steam_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='trade_token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
