# Generated by Django 6.1.1 on 2026-09-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_customuser_steam_id_customuser_trade_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('available', 'Доступен'), ('in_battle', 'В Battle'), ('frozen', 'Заморожен'), ('withdraw_pending', 'Выводится'), ('delivered', 'Выведен'), ('invalid', 'Недействителен'), ('sold', 'Продан')], default='available', max_length=30),
        ),
    ]
