# Generated by Django 6.1.1 on 2026-09-11 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login failed'), ('profile_updated', 'Profile updated'), ('battle_created', 'Battle created'), ('battle_joined', 'Battle joined'), ('battle_left', 'Battle left'), ('bet_placed', 'Bet placed'), ('battle_started', 'Battle started'), ('battle_finished', 'Battle finished'), ('battle_cancelled', 'Battle cancelled'), ('item_received', 'Item received'), ('item_locked', 'Item locked'), ('item_unlocked', 'Item unlocked'), ('item_sold', 'Item sold'), ('withdraw_requested', 'Withdraw requested'), ('item_withdrawn', 'Item withdrawn'), ('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('bet_charge', 'Bet charge'), ('win', 'Win'), ('commission', 'Commission'), ('shop_purchase', 'Shop purchase'), ('shop_sale', 'Shop sale'), ('user_banned', 'User banned'), ('user_unbanned', 'User unbanned'), ('role_changed', 'Role changed'), ('user_activated', 'User activated')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
